### PR TITLE
change api root [#89]

### PR DESCRIPTION
**Pull request by ToBinio**
- [Userstory #89](https://tree.taiga.io/project/jonaspfeifer05-loggeroo/us/89)

- [Task #111](https://tree.taiga.io/project/jonaspfeifer05-loggeroo/task/111)

### CODE REVIEW

**Review by JonasPfeifer05 — APPROVED** [review]
ok

**Comment by JonasPfeifer05** [comment]
PLEASE change title to [#89]
and add
- [Userstory #89](https://tree.taiga.io/project/jonaspfeifer05-loggeroo/us/89)

**Review by JonasPfeifer05 — DISMISSED** [review]
see chat

**Review by ToBinio — COMMENTED** [review]
LBTO

**Review by xFizzar — APPROVED** [review]

**Pull request merged**
